[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."stripe-webhook"]
  raw_body = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/01_premium.html"
  to = "/premium?unit=01"
  status = 301
  force = true

[[redirects]]
  from = "/02_premium.html"
  to = "/premium?unit=02"
  status = 301
  force = true

[[redirects]]
  from = "/03_premium.html"
  to = "/premium?unit=03"
  status = 301
  force = true

[[redirects]]
  from = "/04_premium.html"
  to = "/premium?unit=04"
  status = 301
  force = true

[[redirects]]
  from = "/05_premium.html"
  to = "/premium?unit=05"
  status = 301
  force = true

[[redirects]]
  from = "/06_premium.html"
  to = "/premium?unit=06"
  status = 301
  force = true

[[redirects]]
  from = "/07_premium.html"
  to = "/premium?unit=07"
  status = 301
  force = true

[[redirects]]
  from = "/08_premium.html"
  to = "/premium?unit=08"
  status = 301
  force = true

[[redirects]]
  from = "/09_premium.html"
  to = "/premium?unit=09"
  status = 301
  force = true

[[redirects]]
  from = "/10_premium.html"
  to = "/premium?unit=10"
  status = 301
  force = true

[[redirects]]
  from = "/11_premium.html"
  to = "/premium?unit=11"
  status = 301
  force = true

[[redirects]]
  from = "/12_premium.html"
  to = "/premium?unit=12"
  status = 301
  force = true

[[redirects]]
  from = "/13_premium.html"
  to = "/premium?unit=13"
  status = 301
  force = true

[[redirects]]
  from = "/14_premium.html"
  to = "/premium?unit=14"
  status = 301
  force = true

[[redirects]]
  from = "/15_premium.html"
  to = "/premium?unit=15"
  status = 301
  force = true

[[redirects]]
  from = "/netlify/lib/data/*"
  to = "/404"
  status = 404
  force = true


[[redirects]]
  from = "/netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
