// Auto-generated by scripts/build-sw.mjs — do not hand-edit.
const CACHE_NAME = "mymentals-0bc0777907"
const BASE = "/mymentals/"
const PRECACHE_URLS = [
  "/mymentals/apple-touch-icon.png",
  "/mymentals/assets/index-BxebxRYX.js",
  "/mymentals/assets/index-CrIwnIRI.css",
  "/mymentals/favicon-32.png",
  "/mymentals/icon-192.png",
  "/mymentals/icon-512.png",
  "/mymentals/icon-maskable-512.png",
  "/mymentals/index.html",
  "/mymentals/manifest.webmanifest"
]

self.addEventListener('install', event => {
  // Note: no skipWaiting() here. On the very first visit there's no
  // controller, so this worker activates immediately anyway. On a later
  // deploy it parks in "waiting" until the page tells it to take over
  // (see the 'message' handler) — that's what lets the app show a
  // "new version — tap to refresh" prompt instead of swapping assets
  // out from under a running session.
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_URLS))
  )
})

// The page posts this when the user taps "Refresh" on the update prompt.
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(names => Promise.all(names.filter(n => n !== CACHE_NAME).map(n => caches.delete(n))))
      .then(() => self.clients.claim())
  )
})

// { ignoreVary: true } matters: a stored response with a Vary header
// (e.g. "Vary: Origin", which vite's own dev/preview server sends) is
// only matched by Cache.match() if the incoming request's headers agree
// with whatever the original precaching request happened to send. A
// browser-native <script>/<link> subresource load and a page-side
// fetch() call don't necessarily send identical headers, so without this
// option a precached entry can silently miss for one but not the other —
// confirmed directly by instrumenting the match calls, not guessed. We
// deliberately don't care about content negotiation for assets we
// precached by URL, so ignoring Vary here is correct, not just a workaround.
const MATCH_OPTS = { ignoreVary: true }

self.addEventListener('fetch', event => {
  const req = event.request
  if (req.method !== 'GET') return

  // Navigations (e.g. opening the app fresh, or a client-side route like
  // /mymentals/log/new on a hard reload) are served cache-first: the app
  // shell (index.html) comes back instantly from cache, and network is
  // only attempted if that lookup genuinely comes up empty.
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match(BASE + 'index.html', MATCH_OPTS).then(cached => cached || fetch(req))
    )
    return
  }

  event.respondWith(
    caches.match(req, MATCH_OPTS).then(cached => {
      if (cached) return cached
      return fetch(req).then(res => {
        if (res.ok) {
          const copy = res.clone()
          caches.open(CACHE_NAME).then(cache => cache.put(req, copy))
        }
        return res
      }).catch(() => cached)
    })
  )
})

// Check-in reminders, sent by mymentals-push-dispatch.js. The payload is
// deliberately minimal — a generic title/body and a deep-link URL, never
// entry content (that function can't read entry content in the first
// place; the server only ever holds ciphertext and an opaque entry id).
self.addEventListener('push', event => {
  let data = { title: 'Check-in time', body: 'How are you feeling now?', url: BASE }
  try {
    if (event.data) data = { ...data, ...event.data.json() }
  } catch { /* fall back to the default above */ }

  event.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body,
      icon: BASE + 'icon-192.png',
      badge: BASE + 'icon-192.png',
      data: { url: data.url },
    })
  )
})

self.addEventListener('notificationclick', event => {
  event.notification.close()
  const url = event.notification.data?.url || BASE
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clientsList => {
      for (const client of clientsList) {
        if (client.url.includes(url) && 'focus' in client) return client.focus()
      }
      // No matching window open — focus any existing tab and navigate it,
      // or open a fresh one if nothing's open at all.
      if (clientsList.length > 0 && 'navigate' in clientsList[0]) {
        return clientsList[0].focus().then(() => clientsList[0].navigate(url))
      }
      return self.clients.openWindow(url)
    })
  )
})
