// Auto-generated by scripts/build-sw.mjs — do not hand-edit.
const CACHE_NAME = "mymentals-671551ea58"
const BASE = "/mymentals/"
const PRECACHE_URLS = [
  "/mymentals/apple-touch-icon.png",
  "/mymentals/assets/index-DC4VPabs.css",
  "/mymentals/assets/index-Eqs9w6G5.js",
  "/mymentals/favicon-32.png",
  "/mymentals/icon-192.png",
  "/mymentals/icon-512.png",
  "/mymentals/icon-maskable-512.png",
  "/mymentals/index.html",
  "/mymentals/manifest.webmanifest"
]

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(names => Promise.all(names.filter(n => n !== CACHE_NAME).map(n => caches.delete(n))))
      .then(() => self.clients.claim())
  )
})

// { ignoreVary: true } matters: a stored response with a Vary header
// (e.g. "Vary: Origin", which vite's own dev/preview server sends) is
// only matched by Cache.match() if the incoming request's headers agree
// with whatever the original precaching request happened to send. A
// browser-native <script>/<link> subresource load and a page-side
// fetch() call don't necessarily send identical headers, so without this
// option a precached entry can silently miss for one but not the other —
// confirmed directly by instrumenting the match calls, not guessed. We
// deliberately don't care about content negotiation for assets we
// precached by URL, so ignoring Vary here is correct, not just a workaround.
const MATCH_OPTS = { ignoreVary: true }

self.addEventListener('fetch', event => {
  const req = event.request
  if (req.method !== 'GET') return

  // Navigations (e.g. opening the app fresh, or a client-side route like
  // /mymentals/log/new on a hard reload) are served cache-first: the app
  // shell (index.html) comes back instantly from cache, and network is
  // only attempted if that lookup genuinely comes up empty.
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match(BASE + 'index.html', MATCH_OPTS).then(cached => cached || fetch(req))
    )
    return
  }

  event.respondWith(
    caches.match(req, MATCH_OPTS).then(cached => {
      if (cached) return cached
      return fetch(req).then(res => {
        if (res.ok) {
          const copy = res.clone()
          caches.open(CACHE_NAME).then(cache => cache.put(req, copy))
        }
        return res
      }).catch(() => cached)
    })
  )
})
